### ISSUE TITLE
how to set the email body?

### ISSUE THREAD

**Issue by Lefthandmedia** [gadgetto/UserImport#10]
Hi 
Under the tab 'Notification Template' i can fill out a subject and email body. And in the system settings i can set an 'emailtemplate'. So how can i make sure the emailtemplate form the system settings is used. I tried having an empty mailbody field under the 'Notification Template' but no luck.

tnx
RDG

**Comment by gadgetto** [comment]
The mailbody field holds the full email template. No other chunks or templates are involved. The corresponding system setting only stores the content of the mail body field, so you can reuse it later.

As this is no issue, I’m closing this.

**Comment by Lefthandmedia** [comment]
Hi,
So does this mean i can change the template chunk to edit the mailbody? or do i have to edit the field and the mailbodyonly gets stored in the chunk?
because  it would be nice if the chunk can be leading. I have all my chunks and snippets as files in a project and import thhem with element helper

tnx 
RDG


On 15 August 2018 at 22:57:25, Martin Gartner (notifications@github.com) wrote:

The mailbody field holds the full email template. No other chunks or templates are involved. The corresponding system setting only stores the content of the mail body field, so you can reuse it later.

As this is no issue, I’m closing this.

**Comment by gadgetto** [comment]
No, User Import doesn’t use a MODX chunk for the mailbody. The mailbody field IS the template/chunk.
