### ISSUE TITLE
Import Freezes

### ISSUE THREAD

**Issue by Manny0114** [gadgetto/UserImport#13]
Hello, I am trying to run this extra with test data. One issue I run into is that it tells me to enter a subject for the email. I am able to remove the error by just clicking on the Notification Template tab, and coming back to the main tab. However, I then get this: 
```
Console running...
Preparing CSV import...
Importing CSV file testusers.csv
Batch size: 0
```
Nothing happens after this. The database also does not get updated, so it is not importing the users. This is the data in the csv file, please let me know if I am missing anything. (I have removed my email):
```
"email","password"
"myemail","test1234"
"myemail","test3333"
```
I saw a closed issue that seemed to be fixed by updating php, but this site on modx cloud running on 7.3. Any help would be appreciated, let me know if you need anything else from me. Thank you.

**Comment by gadgetto** [comment]
Which MODX version?
Do you have any related entries in MODX error log?

**Comment by gadgetto** [comment]
Closed since no response - feel free to reopen if necessary
