### ISSUE TITLE
Does not work in MODX 3

### ISSUE THREAD

**Issue by Egmund** [gadgetto/UserImport#14]
Does not work in MODX 3. I get a blank screen.

**Comment by dimasites** [comment]
Hi @Egmund , please say you are using 2.x version of Userimport in MODX3, or 1.x Userimport  version (whitch for MODX2) in MODX3 ?

**Comment by gadgetto** [comment]
UserImport 1.x is for MODX 2.x only.
UserImport 2.x is for MODX 3.x only.

The MODX3 standalone version (UserImport 2.x) is coming soon! Just finishing last tasks and submitting a transport package to MODX extras provider. Please stay tuned ...

**Comment by gadgetto** [comment]
Fixed in 2.0.0-beta1
