### ISSUE TITLE
Enhancement : extented fields support

### ISSUE THREAD

**Issue by jchirschy** [gadgetto/UserImport#4]
Hello,

Very nice extra.
Is it technically possible to support the importation of extended fields ? 
I have to set some more fields from a existing database and in particular a field that will serve as a foreign key.
Would you consider upgrading this extra in this way ? or giving some useful tips to achieve this ?

Thanks in advance
JeanClaude

**Comment by gadgetto** [comment]
This can be integrated but needs some time. Definitely a needed feature! I'll put it on the list.

**Comment by jaygilmore** [comment]
Hi @gadgetto any thoughts on how much effort this might be to complete? I absolutely understand it may be a how long is a piece of string question. : )

**Comment by gadgetto** [comment]
@jaygilmore I'll do my best to implement this as soon as possible! :-)
Currently very busy...

**Comment by gadgetto** [comment]
Feature implemented! :-) @jaygilmore 
See updated instructions at http://www.bitego.com/extras/userimport/
