### ISSUE TITLE
Enhancement : Sending an validation's email to the imported users

### ISSUE THREAD

**Issue by jchirschy** [gadgetto/UserImport#5]
Hello

In order to get a seamless experience, is it possible to send an email to the newly imported user for validation and welcoming purpose ?

Thanks for your support or your tips.
JeanClaude

**Comment by gadgetto** [comment]
That's a good request! I will put it on the list!

**Comment by maxgolv** [comment]
Hello.
Thank you for your extra really helped me. But I would like to know about issue # 5, will it be implemented?
Sorry for my English)

**Comment by gadgetto** [comment]
Hi,

we are currently busy with other projects, so this feature won’t be ready soon. Sorry!

Greetings,
Martin

**Comment by Lefthandmedia** [comment]
Did this get implemented yet? i need it as well

**Comment by gadgetto** [comment]
Still not implemented.

**Comment by gadgetto** [comment]
Implemented with 1.1.0-rc1
