### ISSUE TITLE
Manually set initial password for each imported user

### ISSUE THREAD

**Issue by bwente** [gadgetto/UserImport#7]
What did I miss? Are passwords automatically created? I was going to use a field to set the password for the first time, like phone or dob. Then require them to change it on first login.

**Comment by gadgetto** [comment]
Passwords are currently generated automatically (random). But you are right, this should be more configurable! I'll take this as a feature request.

Currently an imported user needs to reset his password with the "forgot password" feature of MODX.

An idea how we should handle this? Send user an email with his randomly generated password?

**Comment by bwente** [comment]
Something like this?
http://rtfm.modx.com/extras/revo/login/login.register#Login.Register-SendinganActivationEmail

Don't need to reinvent the wheel...
https://github.com/modxcms/Login

**Comment by Jenzemann** [comment]
The possibility to set an first time password manually with a field in the CSV would also be handy.

**Comment by Lefthandmedia** [comment]
Has this been implemented?

**Comment by gadgetto** [comment]
Yes! UserImport can generate passwords for you or you can import the password per user via CSV.
