### ISSUE TITLE
Freeze on import

### ISSUE THREAD

**Issue by clutchmarketing** [gadgetto/UserImport#9]
Hi, tried using this plugin in MODX 2.6.0 and when I tried importing a small file (10 users) in the format specified, it just hangs and nothing happens (the Console running... message shows up but nothing happens after that). I doubled checked the db and nothing seems to have been imported.

**Comment by gadgetto** [comment]
Any relevant entries in MODX error log?
Which plugins do you have installed?

**Comment by gadgetto** [comment]
I can't reproduce this on a 2.6 install. Works as expected.

**Comment by clutchmarketing** [comment]
I checked the error log and there is nothing there.
This is the only plugin I have installed since it is new MODX install.  MODX is currently installed in a sub folder (/modx) if that is of significance.

**Comment by gadgetto** [comment]
Server version?
PHP version?
MySQL version?
Is it possible that you send me the CSV file you tried to import?

**Comment by clutchmarketing** [comment]
Turns out it was an old PHP version that the host was using. I had them upgrade to the most recent and that fixed everything.  Thanks very much for your help!

**Comment by gadgetto** [comment]
Thanks for reporting back!
